services:
  ravendb:
    image: ravendb/ravendb:4.2.101-ubuntu.18.04-x64
    environment:
      - RAVEN_EULA_ACCEPTED=true
      - RAVEN_Setup_Mode=None
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
    ports:      
      - '8080:8080' 
    